// random.cc (C) Kai-Uwe Bux [2024]
// ================================

#ifndef RANDOM
#define RANDOM

#include <type_traits>
#include <random>

class uniform_rng {

  typedef unsigned long long uhuge;
  typedef long double        fhuge;
    
  // the entropy source
  // ==================

  unsigned int get_seed ( void ) const {
    std::random_device r_dev; // default constructed
    return ( r_dev() );
  }
  
  // the engine
  // ==========
    
  std::default_random_engine the_urbg;


  // uniform distributions (entropy reservois)
  // =========================================

  using discrete_dist_t    = std::uniform_int_distribution< uhuge >;
  using discrete_param_t   = typename discrete_dist_t::param_type;
  using continuous_dist_t  = std::uniform_real_distribution< fhuge >;
  using continuous_param_t = typename continuous_dist_t::param_type;

  discrete_dist_t    the_discrete_d;
  continuous_dist_t  the_continuous_d;
    

  // generating random numbers
  // =========================
    
  template < typename ArithmeticType >
  ArithmeticType get ( ArithmeticType bound,
                       std::true_type, std::true_type ) {
    // ENFORCE( bound > 0 );
    return ( the_discrete_d( the_urbg, discrete_param_t(0,bound-1) ) );
  }
    
  template < typename ArithmeticType >
  ArithmeticType get ( ArithmeticType a, ArithmeticType b,
                       std::true_type, std::true_type ) {
    // ENFORCE( a <= b );
    return ( a + the_discrete_d( the_urbg, discrete_param_t(0,b-a) ) );
  }
    
  template < typename ArithmeticType >
  ArithmeticType get ( ArithmeticType bound,
                       std::true_type, std::false_type ) {
    // ENFORCE( bound > 0 );
    return ( the_continuous_d( the_urbg, continuous_param_t(0,bound) ) );
  }
    
  template < typename ArithmeticType >
  ArithmeticType get ( ArithmeticType a, ArithmeticType b,
                       std::true_type, std::false_type ) {
    // ENFORCE( a < b );
    return ( the_continuous_d( the_urbg, continuous_param_t(a,b) ) );
  }

    
public:

  // default construct with unpredictable inital state
  // =================================================
  /*
    Different default constructed objects should have
    independent unpredictable initial states.
  */
  uniform_rng ( void )
    : the_urbg ( get_seed() )
    , the_discrete_d ()
    , the_continuous_d ()
  {}

  // forwarding constructors (e.g. for reproducible sequences)
  // =========================================================
  /*
    This may in particular be used to initializ the
    underlying engine object from a seed.
      
    If the template type parameter specifies an engine
    type for which the initial seed defines the entire
    sequence of random numbers generated by an instance,
    then the same will hold for the uniform_rng object
    constructed from a seed.
  */
  template < typename ... Args >
  uniform_rng ( Args && ... args )
    : the_urbg ( std::forward< Args >( args ) ... )
    , the_discrete_d ()
    , the_continuous_d ()
  {}
    
  // copy constructor
  // ================
  uniform_rng ( uniform_rng const & other )
    : the_urbg ( other.the_urbg )
    , the_discrete_d ()
    , the_continuous_d ()
  {}

  uniform_rng ( uniform_rng & other )
    : the_urbg ( other.the_urbg )
    , the_discrete_d ()
    , the_continuous_d ()
  {}


  // return a uniform deviate in [0,bound)
  // =====================================
  /*
    The result type is deduced from the type of the
    bound passed in as a parameter. This also determines
    whether the distribution is continuous or discrete.

    This is designed so that it can be used as a random
    number generator object in algorithms like random_shuffle.

    This should raise a compilation error if the
    parameter does not have an arithmetic type.

    The behavior is undefined if 0 or a negative number
    is passed as the bound.
  */
  template < typename ArithmeticType >
  ArithmeticType operator() ( ArithmeticType bound ) {
    return
      ( get ( bound,
              typename
              std::is_arithmetic< ArithmeticType>::type(),
              typename
              std::is_integral<ArithmeticType>::type() ) );
  }

    
  // return a uniform deviate in [a,b] (integral) or [a,b) (floating point)
  // ======================================================================
  /*
    The result type is deduced from the type of the
    bound passed in as a parameter. This also determines
    whether the distribution is continuous or discrete.

    This is designed so that it mimmiks the behavior of
    uniform_int_distribution and uniform_real_distribution,
    respectively.

    This should raise a compilation error if the
    parameter does not have an arithmetic type.

    The behavior is undefined if b <= a.
  */
  template < typename ArithmeticType >
  ArithmeticType operator() ( ArithmeticType a, ArithmeticType b ) {
    return
      ( get ( a, b,
              typename
              std::is_arithmetic< ArithmeticType>::type(),
              typename
              std::is_integral<ArithmeticType>::type() ) );
  }


  // return a full word of random bits
  uhuge operator() ( void ) {
    return ( get( 0ull, -1ull, std::true_type(), std::true_type() ) );
  }


  // return a coin flip
  // ==================
    
  bool flip ( double p = 0.5 ) {
    return ( this->operator()( 1.0 ) < p );
  }


  // copy constructor and assignment operator
  // ========================================
  /*
    These shall copy the initial state. The compiler
    supplied versions will do that just fine.
  */
    
  // destructor
  // ==========
  /*
    There is no need for this to be virtual.
  */
    
};


#endif // RANDOM

// end of file
